### ISSUE TITLE
Chord Shapes, Chord Symbols, and Chords

### ISSUE THREAD

**Issue by edwisdom** [edwisdom/chords#16]
It'd probably be helpful from a naming and clear-thinking standpoint to distinguish between these such that...

ChordShape <- everything Chord currently is without the Root
ChordSymbol <- Root ChordShape
Chord <- (ChordSymbol, [Note]), i.e. currently ExpChord

These would allow ChordShape to mirror the existing Mode type, and ChordSymbol to mirror the existing Scale type

**Comment by ChrisEPhifer** [comment]
Happy to take this one, regardless of who works on it though, it should probably wait until #17 is merged back into `develop` since it depends on that work somewhat.

**Comment by ChrisEPhifer** [comment]
Actually, I think I'll work on this now even though #17 is WIP. The change is a bit large but should be (mostly) painless to integrate there when the time comes.

**Comment by edwisdom** [comment]
Resolved by #19
